CerconeGrimoireData = {
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Asesinato",
        Orden="1",
        Descripcion="Enfoque implacable: Concentras tus sentidos, realizando daño preciso con un arco espectral.",
        Valores="Acción, Ataque +2, Coste 1 Mag.",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Asesinato",
        Orden="2",
        Descripcion="Marca del Segador: Expone las debilidades del enemigo por un turno, lo que reduce su resistencia física y a hechizos.",
        Valores="Acción Adicional, Habilidad en combate, -2 def al oponente por 1 turno, Coste 2 Mag.",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Asesinato",
        Orden="3",
        Descripcion="Golpe incapacitante: Lanza un ataque a un enemigo que esté dentro del rango de visión con un golpe relámpago aturdiéndolo durante 5 minutos.",
        Valores="Acción, Utilitaria fuera de combate, 1 uso al día, coste 0 Mag.",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sombra",
        Orden="1",
        Descripcion="Capa Oscura: Te fundes con las sombras para hacerte invisible evadiendo los ataques físicos y de hechizo, otorgando un +2 a tu defensa hasta que se consuma con el siguiente ataque recibido.",
        Valores="Acción, Habilidad fuera de combate, 1 uso al día, coste 0 Mag.",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sombra",
        Orden="2",
        Descripcion="Sendero de oscuridad: Crea un pasillo sombrío que causa daño a un oponente.",
        Valores="Acción, Ataque +3, Coste 2 Mag.",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sombra",
        Orden="3",
        Descripcion="Invocar Sombra: Invocas una versión fantasmal de ti mismo que luchará a tu lado y atacara durante tu turno causando daño al oponente. Tras acabar el turno la sombra desaparecerá.",
        Valores="Acción, Ataque +4, Coste 3 Mag.",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Succion",
        Orden="1",
        Descripcion="Drenar esencia: Extrae el vigor de la sangre de tus oponentes infligiendoles daño.",
        Valores="Acción, Ataque en área +1, Coste 3 Mag.",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Succion",
        Orden="2",
        Descripcion="Canalización de salud: Canaliza la sangre en ti y tus aliados para curar sus heridas.",
        Valores="Acción, Sanación +3 HP y +3 HP a 2 aliados adicionales, Coste 6 Mag.",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Succion",
        Orden="3",
        Descripcion="Sacrificio Sanguíneo: Vierte tu propia sangre recibiendo 1 pt de daño y la canalizas en un aliado para curarle. O canalizas la sangre de un aliado causandole 1pt de daño para curarte a ti mismo.",
        Valores="Acción, Sanación +5 HP, Coste 3 Mag y 1 HP.",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Señor sepulcral",
        Orden="1",
        Descripcion="Reanimar Cadáver: Reanima un cadáver de la tierra que luchará a tu lado y atacara durante tu turno causando daño nigromántico. Tras acabar el combate el cadáver se descompondrá.",
        Valores="Acción, Ataque +2, requiere cadáveres o un Tótem de hueso, Coste 1 Mag.",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Señor sepulcral",
        Orden="2",
        Descripcion="Explosión Pestífera: Comanda a tu putrefacta reanimación a correr hacia el objetivo y explotando cuando esté cerca, infligiendo daño de enfermedad a tu objetivo.",
        Valores="Acción, Ataque +4, requiere un cadáver reanimado, Coste 3 Mag.",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Señor sepulcral",
        Orden="3",
        Descripcion="Coloso pestilente: Desata un pestilente coloso de carne que pulverizará golpeando el suelo tres veces en un turno a los enemigos en la zona.",
        Valores="Acción, Ataque en área +1, coste 3 Mag.",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Tirano de los huesos",
        Orden="1",
        Descripcion="Guadaña de la muerte: Convierte tu arma actual en una guadaña de energía nigromántica, desgarra la fuerza vital de tu enemigo, infligiendo daño nigromántico. Tu arma vuelve a la normalidad al final del turno.",
        Valores="Acción, Ataque +3, Coste 2 Mag.",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Tirano de los huesos",
        Orden="2",
        Descripcion="Armadura de hueso: Te envuelve en duros huesos, aumentando la resistencia física y a hechizos hasta que se consuma con el siguiente ataque recibido.",
        Valores="Reacción, Defensa +2, Coste 2 Mag.",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Tirano de los huesos",
        Orden="3",
        Descripcion="Tótem de hueso: Invoca una efigie de hueso a tus pies que funciona como fuente de cadáveres para invocar las habilidades que requieren cadáveres.",
        Valores="Acción Adicional, Habilidad en combate, 1 uso al día, Coste 0 Mag.",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Muerte encarnada",
        Orden="1",
        Descripcion="Vida entre la muerte: Consume los cadáveres de los caídos para sanarte a ti y a tus aliados.",
        Valores="Acción, Sanación +3 HP y +3 HP a 2 aliados adicionales, Coste 6 Mag.",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Muerte encarnada",
        Orden="2",
        Descripcion="Reanimar: Levanta a tus aliados vampiros al borde de la muerte y los devuelve a su estado consciente con la mitad de sus HP.",
        Valores="Acción, Habilidad en combate, Coste 2 Mag.",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Muerte encarnada",
        Orden="3",
        Descripcion="Sanación de carne: Sacrificas parte de tu propia esencia de vida recibiendo 1 pt de daño para reparar la carne dañada de un aliado curándole 5 pts de HP.",
        Valores="Acción, Sanación +5 HP, Coste 3 Mag.",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Emisario del Tomo",
        Orden="1",
        Descripcion="Forjador del destino: Canaliza tu conocimiento puro en un haz de energía que deja cicatrices en el mundo que tienes ante ti. Dirige el rayo durante un turno causando daño a tu oponente.",
        Valores="Acción, Ataque +4, Coste 3 Mag.",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Emisario del Tomo",
        Orden="2",
        Descripcion="Flagelo del Cefaliarca: Te imbuye magia abisal en el brazo para formar tentáculos que arremeten contra tus enemigos, lo que les causa daño físico.",
        Valores="Acción, Ataque +3, Coste 2 Mag.",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Emisario del Tomo",
        Orden="3",
        Descripcion="Ojo impasible: Rasga el tejido del Aurbis para invocar un vástago de Hermaeus Mora. Este ser crea un haz que desgarra la realidad durante un turno e inflige daño a todos los oponentes.",
        Valores="Acción, Ataque en área +1, coste 3 Mag.",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Soldado de Apocrypha",
        Orden="1",
        Descripcion="Convulsión rúnica: Crea una runa de Apocrypha que inflige daño mágico al oponente.",
        Valores="Acción, Ataque +2, Coste 1 Mag.",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Soldado de Apocrypha",
        Orden="2",
        Descripcion="Protección rúnica impenetrable: Invoca un escudo rúnico que absorbe el de daño, aumentando tu resistencia física y a hechizos hasta que se consuma con el siguiente ataque recibido.",
        Valores="Reacción, Defensa +2, Coste 2 Mag.",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Soldado de Apocrypha",
        Orden="3",
        Descripcion="Runa del horror sobrenatural: Graba una runa incomprensible en la mente del enemigo, causando una reducción en la defensa del enemigo.",
        Valores="Acción Adicional, Habilidad en combate, -2 def al oponente por 1 turno, Coste 2 Mag.",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Formas rúnicas curativas",
        Orden="1",
        Descripcion="Oleada curativa: Canaliza el mar abisal para concentrarlo en un rayo que te cura a ti o a los aliados que están en su trayectoria.",
        Valores="Acción, Sanación +5 HP, Coste 3 Mag.",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Formas rúnicas curativas",
        Orden="2",
        Descripcion="Pasadizo entre mundos: Rompe los muros del mundo para crear un portal en el lugar elegido. Su homólogo aparece justo ante de ti. Cruzar el umbral te permite teletransportarte de uno a otro mientras los portales siguen abiertos. Los aliados que se encuentran dentro de cualquiera de los portales pueden teletransportarse al otro portal.",
        Valores="Acción, Habilidad fuera de combate, 1 uso al día, coste 0 Mag.",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Formas rúnicas curativas",
        Orden="3",
        Descripcion="Dominio de arcanista: Utilizas tu tomo para invocar el vigoratum de Hermaeus Mora y así conjurar un vórtice de sanación sobrenatural, invocar este vórtice permite sanar tus heridas y las de tus aliados.",
        Valores="Acción, Sanación fuera de combate, +5 HP (se pueden repartir), 1 uso al día, Coste 0 Mag.",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Fuego ardiente",
        Orden="1",
        Descripcion="Latigazo ardiente: Azotas al enemigo con un látigo de fuego, infligiéndole daño llama.",
        Valores="Acción, Ataque +2, Coste 1 Mag.",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Fuego ardiente",
        Orden="2",
        Descripcion="Aliento abrasador: Exhala una explosión flamante contra el oponente que haya frente a ti y le infliges daño llama.",
        Valores="Acción, Ataque +3, Coste 2 Mag.",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Fuego ardiente",
        Orden="3",
        Descripcion="Estandarte de caballero dragón: Invoca un estandarte de batalla que te inspira y a tus aliados aumentado su daño realizado.",
        Valores="Acción Adicional, Habilidad en combate, +1 bonificador de ataque a ti y 3 aliados por un turno, Coste 2 Mag.",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Poder draconiano",
        Orden="1",
        Descripcion="Armadura endurecida: Liberas a tu dragón interior para obtener un escudo de espinas, aumentando tu resistencia física y a hechizos hasta que se consuma con el siguiente ataque recibido.",
        Valores="Reacción, Defensa +2, Coste 2 Mag.",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Poder draconiano",
        Orden="2",
        Descripcion="Garras oscuras: Conjura garras provenientes del suelo que inmoviliza al oponente, provocándole perder por 1 turno.",
        Valores="Acción, Habilidad en combate, Coste 3 Mag.",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Poder draconiano",
        Orden="3",
        Descripcion="Salto de dragón: Te abalanzas sobre un enemigo, infligiendo daño físico a todos los oponentes.",
        Valores="Acción, Ataque en área +1, Coste 3 Mag.",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Corazón de tierra",
        Orden="1",
        Descripcion="Nube de cenizas: Invoca una nube de ceniza en tu ubicación, al rededor tuyo, curándote.",
        Valores="Acción, Sanación +5 HP, Coste 3 Mag.",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Corazón de tierra",
        Orden="2",
        Descripcion="Puño de piedra: Golpea al suelo con tus pies, alzando escombros del suelo que flotarán a tu alrededor durante 1 turno, permitiéndote lanzarlos a un enemigo, infligiendo daño físico.",
        Valores="Acción, Ataque +4, Coste 3 Mag.",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Corazón de tierra",
        Orden="3",
        Descripcion="Petrificación: Envuelve a un enemigo en piedra fundida, lo cual lo aturde.",
        Valores="Acción, Habilidad fuera de combate, 1 uso al día, coste 0 Mag.",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Magia oscura",
        Orden="1",
        Descripcion="Intercambio Oscuro: Realizas un intercambio con los fragmentos de cristal daédrico para extraer su energía y así recuperar tu salud.",
        Valores="Acción, Sanación +5 HP, Coste 3 Mag.",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Magia oscura",
        Orden="2",
        Descripcion="Mortaja vibrante: Invoca un manto daédrico que surge de Oblivion y te envuelve para curarte a ti y a tus aliados.",
        Valores="Acción, Sanación +3 HP y +3 HP a 2 aliados adicionales, Coste 6 Mag.",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Magia oscura",
        Orden="3",
        Descripcion="Minas daédricas: Sorprende a tu enemigos colocando una mina daédrica explosiva a sus pies, cuando se detona la mina, la explosión inflige daño mágico a tu oponente.",
        Valores="Acción, Ataque +3, Coste 2 Mag.",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Invocación daédrica",
        Orden="1",
        Descripcion="Invocar familiar inestable: Domina los poderes de Oblivion para que envíen a un familiar daédrico con 1 pt de HP (Scamp o Clanfear). Puedes comandar a tu familiar para que realiza tareas mundanas.",
        Valores="Acción, Habilidad fuera de combate, 1 uso al día, coste 0 Mag.",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Invocación daédrica",
        Orden="2",
        Descripcion="Invocar matriarca crepuscular: Invocas una matriarca crepuscular que puedes comandar para que debilite la defensa de tu oponente.",
        Valores="Acción Adicional, Habilidad en combate, -2 def al oponente por 1 turno, Coste 2 Mag.",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Invocación daédrica",
        Orden="3",
        Descripcion="Égida vinculada: Te proteges con el poder de Oblivion y creas una cota de malla daédrica que aumenta tu resistencia física y a hechizos hasta que se consuma con el siguiente ataque recibido.",
        Valores="Reacción, Defensa +2, Coste 2 Mag.",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Llamada de la tormenta",
        Orden="1",
        Descripcion="Torrente de relámpagos: Crea un nexo de energía tormentosa en una ubicación específica, que inflige daño de descarga eléctrica a tus oponentes.",
        Valores="Acción, Ataque en área +1, Coste 3 Mag.",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Llamada de la tormenta",
        Orden="2",
        Descripcion="Sobrecarga de energía: Carga tus puños con el poder de la tormenta, para lanzar proyectiles de relámpago, infligiendo daño de descarga eléctrica a un oponente a distancia.",
        Valores="Acción, Ataque +2, Coste 1 Mag.",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Llamada de la tormenta",
        Orden="3",
        Descripcion="Bola de relámpagos: Conviértete en energía pura y lánzate hacia adelante, causando daño de descarga eléctrica a tu oponente cerca del punto de llegada.",
        Valores="Acción, Ataque +4, Coste 3 Mag.",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Acompañantes animales",
        Orden="1",
        Descripcion="Asalto subterráneo: Desata a un grupo de Shalk que ataca, infligiendo daño de veneno al oponente que se encuentre frente a ti.",
        Valores="Acción, Ataque +4, Coste 3 Mag.",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Acompañantes animales",
        Orden="2",
        Descripcion="Moscas infestas: Libera un enjambre de Moscas que atacan a un enemigo e infligen daño de enfermedad durante un turno.",
        Valores="Acción, Ataque +2, Coste 1 Mag.",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Acompañantes animales",
        Orden="3",
        Descripcion="Netch azul: Invoca a una Netch que te ayuda explorando y buscando el área.",
        Valores="Acción, Habilidad fuera de combate, +3 en una prueba de Exploración y Búsqueda, 1 uso al día, coste 0 Mag.",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Equilibrio verde",
        Orden="1",
        Descripcion="Proliferación fúngica: Crea una extensa zona de hongos frente a ti, curándote a ti o a un aliado.",
        Valores="Acción, Sanación +5 HP, Coste 3 Mag.",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Equilibrio verde",
        Orden="2",
        Descripcion="Semilla sanadora: Invoca un campo de flores que florecen, curándote y 2 aliados mas.",
        Valores="Acción, Sanación +3 HP y +3 HP a 2 aliados adicionales, Coste 6 Mag.",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Equilibrio verde",
        Orden="3",
        Descripcion="Abrazo de la naturaleza: Lanza una enredadera que te permite restaurar tus efectos negativos o los de aliado.",
        Valores="Acción Adicional, Habilidad en combate, Elimina 2 efectos dañinos en ti o un aliado, Coste 2 Mag.",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Abrazo invernal",
        Orden="1",
        Descripcion="Escudo cristalizado: Creas un grueso escudo de hielo a tu alrededor, que te proporciona resistencia física y a hechizos hasta que se consuma con el siguiente ataque recibido.",
        Valores="Reacción, Defensa +2, Coste 2 Mag.",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Abrazo invernal",
        Orden="2",
        Descripcion="Fragmentos penetrantes: Conjura fragmentos glaciales a tu alrededor que atravesarán al oponente que esté cerca tuyo, causando daño escarcha.",
        Valores="Acción, Ataque +3, Coste 2 Mag.",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Abrazo invernal",
        Orden="3",
        Descripcion="Tormenta del norte: Levanta una violenta tormenta a tu alrededor, causando daño a todos los oponentes cercanos.",
        Valores="Acción, Ataque en área +1, Coste 3 Mag.",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Lanza Daédrica",
        Orden="1",
        Descripcion="Golpes Perforantes: Lanzas un asalto implacable, golpeando a los enemigos que hay frente a ti varias veces con una lanza mágica, infligiendo daño al enemigo.",
        Valores="Acción, Ataque +3, Coste 2 Mag.",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Lanza Daédrica",
        Orden="2",
        Descripcion="Fragmentos de Lanza: Lanzas la lanza hacía los cielos para invocar una lluvia de ira profana, infligiendo daño a los enemigos que se encuentren en la zona.",
        Valores="Acción, Ataque en área +1, Coste 3 Mag.",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Lanza Daédrica",
        Orden="3",
        Descripcion="Escudo Solar: Te envuelves con rayos solares profanos para crear un escudo que revela objetos o personas invisibles.",
        Valores="Acción, Habilidad fuera de combate, 1 uso al día, coste 0 Mag.",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Ira del ocaso",
        Orden="1",
        Descripcion="Nova: Conjura un fragmento profano, que al caer inflige gran daño al enemigo.",
        Valores="Acción, Ataque +4, Coste 3 Mag.",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Ira del ocaso",
        Orden="2",
        Descripcion="Destello Oscuro: Conjura una bola de energía profana que lanzas al objetivo, infligiéndole daño.",
        Valores="Acción, Ataque +2, Coste 1 Mag.",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Ira del ocaso",
        Orden="3",
        Descripcion="Oscuridad Encarnada: Te envuelve en una esfera de oscuridad que te protege al recibir daño directo.",
        Valores="Reacción, Defensa +2, Coste 2 Mag.",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Oscuridad restauradora",
        Orden="1",
        Descripcion="Aura Restauradora: Defiende la causa de la gloria vampírica y consagras las almas de los caídos para sanarte o a tus aliados cercanos.",
        Valores="Acción, Sanación +5 HP, Coste 3 Mag.",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Oscuridad restauradora",
        Orden="2",
        Descripcion="Ritual Purificador: Enaltece a los daedra para curar tu cuerpo y de tus aliados al instante.",
        Valores="Acción, Sanación +3 HP y +3 HP a 2 aliados adicionales, Coste 6 Mag.",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Oscuridad restauradora",
        Orden="3",
        Descripcion="Runa de Focalización: Creas una runa de protección profana en el suelo que permite la purificación de tu cuerpo quitando efectos dañinos de tu cuerpo.",
        Valores="Acción Adicional, Habilidad en combate, Elimina 2 efectos dañinos en ti o un aliado, Coste 2 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de una mano",
        Orden="1",
        Descripcion="Doble Arma: Entrenamiento en el combate utilizando dos armas de una mano.",
        Valores="Acción, Ataque +1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de una mano",
        Orden="2",
        Descripcion="Arma y escudo: Entrenamiento en el combate con un arma de una mano y escudo.",
        Valores="Acción, Ataque +1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de dos manos",
        Orden="1",
        Descripcion="Manodoble: Entrenamiento en el combate con un arma de dos manos.",
        Valores="Acción, Ataque +1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de dos manos",
        Orden="2",
        Descripcion="Arqueria: Entrenamiento en el combate con arcos cortos y arcos largos.",
        Valores="Acción, Ataque +1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Bastones",
        Orden="1",
        Descripcion="Bastones de destrucción: Capacidad de lanzar ataques de fuego, hielo y electricidad.",
        Valores="Acción, Ataque +1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Bastones",
        Orden="2",
        Descripcion="Bastones de restauración: Capacidad de sanar y lanzar ataques de energía.",
        Valores="Acción, Ataque +1, Coste 0 Mag. / Acción, Sanación +1 HP a 2 aliados, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Técnicas adicionales",
        Orden="1",
        Descripcion="Armas de Asedio: Capacitación para operar las siguientes armas de asedio contra estructuras:",
        Valores="Balistas: Acción, Ataque +3, Ventaja contra armas de asedio, Desventaja contra oponentes en movimiento Coste 0 Mag.\nCatapultas: Acción, Ataque +6, 1 turno de recarga. [0 turno de recarga si hay 1 persona asistiendo].\nTrabuquetes: Acción, Ataque +12, 1 turno de recarga, requiere 2 personas.\nArietes: Acción, Ataque +9 y +3 adicional por cada persona asistiendo [max +18], requiere 3-6 personas.",
    },
    {
        Z="9",
        Nombre="Linaje Cercone",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Seducción Vampírica: Controla la mente de tu oponente causando que el obedezca tu mandato.",
        Valores="Acción, Habilidad fuera de combate, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="9",
        Nombre="Linaje Cercone",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Forma de Niebla: Te conviertes en neblina desplazándote 10 mts evitando ser avistado durante su duración, evitando trampas en el recorrido.",
        Valores="Acción, Habilidad fuera de combate, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="9",
        Nombre="Linaje Cercone",
        NombreRama="Bloque 3",
        Orden="3",
        Descripcion="Vástago de Sangre: Te transformas en Vástago de Sangre alterando tu forma drásticamente, sanándote y mejorando por un turno tu fuerza de ataque y tu defensa. Si usas esta habilidad en exteriores durante el día recibes 2 pt de daño.",
        Valores="Acción, Ataque +5, Defensa +5, +5 HP, 1 turno, 1 uso al día, (-2 HP, si se usa en exteriores durante el día).",
    },
    {
        Z="10",
        Nombre="Linaje Indómito",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Presencia Indómita: Según la marca obtenida en tu ritual, dicha luna te otorgara un bonificación.\nMasser: Tirada de ventaja en Intimidar\nSecunda: Tirada de ventaja en Persuadir\nLuna Obscura: Tirada de ventaja en Intimidar y Persuadir",
        Valores="Acción, Habilidad fuera de combate, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="10",
        Nombre="Linaje Indómito",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Impulso Feral: Saltas impulsado por tu naturaleza feral desplazándote 10 mts evitando ser avistado durante su duración, evitando trampas en el recorrido.",
        Valores="Acción, Habilidad fuera de combate, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="10",
        Nombre="Linaje Indómito",
        NombreRama="Bloque 3",
        Orden="3",
        Descripcion="Llamado de la Manada: Invocas 2 lobos para causar un ataque o entras en Berserker potenciando tu forma drásticamente, sanándote y mejorando por un turno tu fuerza de ataque y tu defensa. Por cada Lycan Indómito tu ataque se ve potenciado.",
        Valores="Acción, Ataque +3 (y +1 adicional por cada Lyacn Indómito presente), Defensa +5, +5 HP, 1 turno, 1 uso al día.",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Custodes",
        Orden="1",
        Descripcion="En Construccion",
        Valores="Ataque +2, 2pt adicionales de daño por turno durante 3 turnos, +3 magicka, 1 uso al día, Ultimate.",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Sanguinaris",
        Orden="2",
        Descripcion="Maniobras de Combate: Soplas un cuerno que eleva la moral de tus aliados, potenciando sus ataques un +1, mientras realizas un ataque especial de +2 a un oponente, provocándole sangrado.",
        Valores="Acción Élite, Ataque +2 provoca Sangrado causando 2pt adicionales de daño por turno durante 3 turnos, Bonificación +1 al ataque de aliados cercanos por 1 turno, 1 uso al día.",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Sombras",
        Orden="3",
        Descripcion="En Construccion",
        Valores="Ataque +2, 2pt adicionales de daño por turno durante 3 turnos, 1 ataque básico adicional ese mismo turno, 1 uso al día, Ultimate",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Inquisidores",
        Orden="4",
        Descripcion="Bendición Marchita: Realizas un rezo a la Dama de los Lamentos suplicando su ayuda, recibiendo así un +4 a una tirada de elección, esto se puede usar 1 sola vez al día.",
        Valores="Acción Elite, +4 a elección",
    },
    {
        Z="12",
        Nombre="Herrería",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Refuerzos de armadura: Unos refuerzos de armadura que mejoran tu capacidad de resistir golpes fisicos y de hechizos.",
        Valores="Bonificador de Defensa +1 permanente",
    },
    {
        Z="12",
        Nombre="Herrería",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Herrero del Clan: Técnicas avanzadas que requieren de una mayor aptitud física para la fabricación de armas y armaduras.",
        Valores="Bonificador de Fuerza +1 permanente",
    },
    {
        Z="12",
        Nombre="Herrería",
        NombreRama="Bloque 3",
        Orden="3",
        Descripcion="Piedras de afilar y contrapeso: Incorporación del uso de las piedras de afilar para hacer mas daños con las armas cortantes y contrapesos para hacer mas daño con armas contundentes.",
        Valores="Bonificador de +1 a los ataques con Arco, Dagas, Espadas, Hachas y Mazas.",
    },
    {
        Z="13",
        Nombre="Ingeniería de Clockwork",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Ganzúas mejoradas:",
        Valores="Bonificador de Inutilizar Mecanismo +1 permanente",
    },
    {
        Z="13",
        Nombre="Ingeniería de Clockwork",
        NombreRama="Bloque 2",
        Orden="1",
        Descripcion="Fabricante de Clockwork City:",
        Valores="Acción, Ataque +4, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="13",
        Nombre="Ingeniería de Clockwork",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Aturdimiento tonal:",
        Valores="Acción, Stun por 1 turno a un enemigo, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="13",
        Nombre="Ingeniería de Clockwork",
        NombreRama="Bloque 3",
        Orden="1",
        Descripcion="Explosivo:",
        Valores="Acción, Ataque en área +1, 1 uso al día, Coste 0 Mag.",
    },
    {
        Z="14",
        Nombre="Sastrería",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Refuerzos de armadura: Unos refuerzos de armadura que mejoran tu capacidad de resistir golpes fisicos y de hechizos.",
        Valores="Bonificador de Defensa +1 permanente",
    },
    {
        Z="14",
        Nombre="Sastrería",
        NombreRama="Bloque 2",
        Orden="1",
        Descripcion="Armadura Ornamentada: Utiliza tu habilidades de sastre para darte una apariencia mas Noble, y así persuadir mas fácilmente.",
        Valores="Bonificador de persuasión +1 permanente",
    },
    {
        Z="14",
        Nombre="Sastrería",
        NombreRama="Bloque 3",
        Orden="1",
        Descripcion="Empuñadura potenciada: Aprende a fabricar una empuñadura con hilos mágicos que permiten una mejor conducción del ataque mágico.",
        Valores="Bonificador de +1 a los ataques con bastón.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Poción de Regeneración: Bebes una poción previamente creada que cura tus heridas.",
        Valores="Acción adicional, Sanación +3 HP, Coste 0.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 1",
        Orden="2",
        Descripcion="Poción de Magicka: Bebes una poción previamente creada que recupera tu Magicka.",
        Valores="Acción adicional, Recupera +3 Mag, Coste 0.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 2",
        Orden="1",
        Descripcion="Toxicología I Venenos: Lanzas un vial de veneno a tu enemigo causando 2pts de daño cada turno, durante 3 turnos",
        Valores="Acción, Ataque 2pts daño por turno, Duración: 3 turnos, Coste 0 Mag",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Toxicología II Antídotos: Bebes un antídoto previamente preparado que elimina los efectos de envenenamientos.",
        Valores="Acción Adicional, Elimina 2 efectos dañinos en ti, Coste 0 Mag.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 3",
        Orden="1",
        Descripcion="Poción de invisibilidad:  Bebes una poción previamente creada que te hace invisible temporalmente",
        Valores="6 min/2 turnos, Coste 0 Mag.",
    },
}
