CerconePjData = {
    {
        Personaje="Aetherius Amarie",
        ID="@GFox01",
        DataGeneral={
            Raza="Altmer",
            Clase="Brujo",
            Nacimiento="2E 530",
            FechaConvercion="2E 555",
            Sire="Vittorio Cercone",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Akish",
        ID="@Ilarislasus",
        DataGeneral={
            Raza="Argoniano",
            Clase="Nigromante",
            Nacimiento="2E 552",
            FechaConvercion="2E 582",
            Sire="Ri’asda",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="2",
            PorMisiones="0",
            Otros="1",
            MeritosGastados="0",
            TotalMeritos="3",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Alaric Noris",
        ID="@Kevinsito04",
        DataGeneral={
            Raza="Dunmer",
            Clase="Hoja de la noche",
            Nacimiento="1E 642",
            FechaConvercion="2E 583",
            Sire="Vittorio Cercone",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Alberich Trevelyan",
        ID="@eruthian16",
        DataGeneral={
            Raza="Imperial",
            Clase="Brujo",
            Nacimiento="1E 2900",
            FechaConvercion="2E 10",
            Sire="Vittorio Cercone",
            Armadura="Ligera",
            Rango="Primogenito",
            Orden="Inquisidores",
            Especializacion="Incursor",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=20,
        Magicka=13,
        Ataque="1D20",
        Defensa=13,
        Meritos={
            PorPorCampana="0",
            PorTaberna="4",
            PorMisiones="2",
            Otros="7",
            MeritosGastados="0",
            TotalMeritos="13",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=3,
            ArteDeGuerra=6,
            LeccionesClase=9
        },
        HabilidadesNOCombatientes={
            Exploracion=3,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=3,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Alenwen Melethil",
        ID="@Gnosis-Aletheia",
        DataGeneral={
            Raza="Altmer",
            Clase="Nigromante",
            Nacimiento="2E 33",
            FechaConvercion="2E 64",
            Sire="Desconocido",
            Armadura="Ligera",
            Rango="Veterano",
            Orden="Inquisidores",
            Especializacion="Erudito",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=18,
        Magicka=13,
        Ataque="1D20",
        Defensa=13,
        Meritos={
            PorPorCampana="11",
            PorTaberna="13",
            PorMisiones="3",
            Otros="9",
            MeritosGastados="0",
            TotalMeritos="36",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=2
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=3,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=3,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Alessandra Belliaris",
        ID="@GummyKitsu",
        DataGeneral={
            Raza="Breton",
            Clase="Brujo",
            Nacimiento="2E 578",
            FechaConvercion="2E 598",
            Sire="Desconocido ",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="3",
            PorMisiones="0",
            Otros="3",
            MeritosGastados="0",
            TotalMeritos="6",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Alethys Rinori",
        ID="@Gnosis-Aletheia",
        DataGeneral={
            Raza="Dunmer",
            Clase="Hoja de la noche",
            Nacimiento="2E 539",
            FechaConvercion="2E 576",
            Sire="Desconocido ",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="1",
            PorMisiones="2",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="3",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Amitiel Stonemantle",
        ID="@Stonemantle",
        DataGeneral={
            Raza="Dunmer",
            Clase="Brujo",
            Nacimiento="2E 523",
            FechaConvercion="2E 576",
            Sire="Velith Aundae",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Anukkra",
        ID="@xXBALBERITHXX",
        DataGeneral={
            Raza="Breton",
            Clase="Brujo",
            Nacimiento="2E 579",
            FechaConvercion="2E 600",
            Sire="Acxo ",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="4",
            PorTaberna="5",
            PorMisiones="1",
            Otros="2",
            MeritosGastados="0",
            TotalMeritos="12",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Ares Bloodfallen",
        ID="@Vander69",
        DataGeneral={
            Raza="Altmer",
            Clase="Nigromante",
            Nacimiento="1E 2231",
            FechaConvercion="1E 2262",
            Sire="Lamae Bal",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Avelene Shitersyphon",
        ID="@GummyKitsu",
        DataGeneral={
            Raza="Altmer",
            Clase="Nigromante",
            Nacimiento="2E 564",
            FechaConvercion="2E 621",
            Sire="Alessandra Beliaris",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="1",
            PorMisiones="4",
            Otros="3",
            MeritosGastados="0",
            TotalMeritos="9",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Azurakira",
        ID="@Azurakira",
        DataGeneral={
            Raza="Bosmer",
            Clase="Nigromante",
            Nacimiento="2E 533",
            FechaConvercion="N/A",
            Sire="N/A",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Carmilla von Karnstein",
        ID="@Ishtariel-CR",
        DataGeneral={
            Raza="Breton",
            Clase="Nigromante",
            Nacimiento="2E 372",
            FechaConvercion="2E 391",
            Sire="Desconocido",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="3",
            PorMisiones="1",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="4",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Caster Braveshine",
        ID="@CC77",
        DataGeneral={
            Raza="Altmer",
            Clase="Brujo",
            Nacimiento="2E 575",
            FechaConvercion="2E 597",
            Sire="Desconocido ",
            Armadura="Ligera",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=13,
        Ataque="1D20",
        Defensa=13,
        Meritos={
            PorPorCampana="3",
            PorTaberna="2",
            PorMisiones="3",
            Otros="3",
            MeritosGastados="6",
            TotalMeritos="5",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=2
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Crisanto de la Perpetua",
        ID="@MarieKapra0795",
        DataGeneral={
            Raza="Dunmer",
            Clase="Hoja de la noche",
            Nacimiento="2E 507",
            FechaConvercion="2E 585",
            Sire="Barakiel Cainhurst",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Dante",
        ID="@ShadowDante",
        DataGeneral={
            Raza="Breton",
            Clase="Hoja de la noche",
            Nacimiento="1E 2200",
            FechaConvercion="1E 2230",
            Sire="Vaelthor",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Dark Schneider",
        ID="@MillerSigurd",
        DataGeneral={
            Raza="Altmer",
            Clase="Brujo",
            Nacimiento="2E 501",
            FechaConvercion="2E 530",
            Sire="Desconocido ",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Dijormk",
        ID="@Diamoc",
        DataGeneral={
            Raza="Nordico",
            Clase="Caballero Dragón",
            Nacimiento="1E 2812",
            FechaConvercion="1E 2836",
            Sire="Lamae Bal",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Dimeric Direnni",
        ID="@Diamoc",
        DataGeneral={
            Raza="Breton",
            Clase="Nigromante",
            Nacimiento="1E 221",
            FechaConvercion="1E 244",
            Sire="Lamae Bal",
            Armadura="Ligera",
            Rango="Recluta",
            Orden="Sanguinaris",
            Especializacion="Soldado",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=14,
        Magicka=13,
        Ataque="1D20",
        Defensa=13,
        Meritos={
            PorPorCampana="10",
            PorTaberna="8",
            PorMisiones="3",
            Otros="8",
            MeritosGastados="16",
            TotalMeritos="13",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=6,
            LeccionesClase=2
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Dixthra",
        ID="@Kryptha",
        DataGeneral={
            Raza="Nordico",
            Clase="Guardian",
            Nacimiento="2E 471",
            FechaConvercion="2E 501",
            Sire="Desconocido ",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="1",
            PorMisiones="0",
            Otros="2",
            MeritosGastados="0",
            TotalMeritos="3",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Drake",
        ID="@TheSaritama",
        DataGeneral={
            Raza="Khajita",
            Clase="Brujo",
            Nacimiento="2E 560",
            FechaConvercion="N/A",
            Sire="N/A",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Drakozillae ",
        ID="@VALLHALLETA",
        DataGeneral={
            Raza="Argoniano",
            Clase="Nigromante",
            Nacimiento="2E 330",
            FechaConvercion="2E 357",
            Sire="Lamae Bal",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Drek'Khar",
        ID="@Thorigama",
        DataGeneral={
            Raza="Orco",
            Clase="Brujo",
            Nacimiento="2E 561",
            FechaConvercion="2E 591",
            Sire="Desconocido",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Elizabeth Dimitrescu ",
        ID="@eruthian16",
        DataGeneral={
            Raza="Breton",
            Clase="Guardian",
            Nacimiento="2E 597",
            FechaConvercion="2E 616",
            Sire="Desconocido",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="FreeKiller el Chileno",
        ID="@FreeKiller150",
        DataGeneral={
            Raza="Nordico",
            Clase="Brujo",
            Nacimiento="?",
            FechaConvercion="2E 617",
            Sire="Lynivren",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="1",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="2",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Frost Bathory",
        ID="@ThorunnBathory666",
        DataGeneral={
            Raza="Nordico",
            Clase="Caballero Dragón",
            Nacimiento="2E 486",
            FechaConvercion="2E 512",
            Sire="Desconocido ",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="5",
            PorMisiones="3",
            Otros="7",
            MeritosGastados="0",
            TotalMeritos="16",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Gragus el Tuerto",
        ID="@Ishtariel-CR",
        DataGeneral={
            Raza="Dunmer",
            Clase="Arcanista",
            Nacimiento="",
            FechaConvercion="",
            Sire="",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="0",
            PorMisiones="1",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="2",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Grom Barba Negra",
        ID="@MillerSigurd",
        DataGeneral={
            Raza="Orco",
            Clase="Arcanista",
            Nacimiento="2E 500",
            FechaConvercion="2E 539",
            Sire="Valak",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="6",
            PorTaberna="4",
            PorMisiones="0",
            Otros="3",
            MeritosGastados="0",
            TotalMeritos="13",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Hasanir",
        ID="@Thorigama",
        DataGeneral={
            Raza="Khajita",
            Clase="Hoja de la noche",
            Nacimiento="2E 505",
            FechaConvercion="2E 529",
            Sire="Desconocido ",
            Armadura="Ligera",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=13,
        Ataque="1D20",
        Defensa=13,
        Meritos={
            PorPorCampana="4",
            PorTaberna="8",
            PorMisiones="5",
            Otros="7",
            MeritosGastados="4",
            TotalMeritos="20",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=2
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Hell-Ah Dinnok",
        ID="@CC77",
        DataGeneral={
            Raza="Altmer",
            Clase="Nigromante",
            Nacimiento="2E 559",
            FechaConvercion="2E 583",
            Sire="Akish",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Hiebacesnof",
        ID="@hiebacesnof",
        DataGeneral={
            Raza="Guardia Rojo",
            Clase="Brujo",
            Nacimiento="2E 585",
            FechaConvercion="2E 616",
            Sire="Vittorio Cercone",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Hillydan",
        ID="@Michahel112",
        DataGeneral={
            Raza="Dunmer",
            Clase="Hoja de la noche",
            Nacimiento="2E 596",
            FechaConvercion="2E 619",
            Sire="Malfurion",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="1",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="1",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Ishtariel Cercone",
        ID="@Ishtariel-CR",
        DataGeneral={
            Raza="Dunmer",
            Clase="Hoja de la noche",
            Nacimiento="2E 549",
            FechaConvercion="2E 582",
            Sire="Desconocido",
            Armadura="Pesada",
            Rango="Veterano",
            Orden="Sanguinaris",
            Especializacion="Soldado",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=18,
        Magicka=10,
        Ataque="1D20",
        Defensa=16,
        Meritos={
            PorPorCampana="18",
            PorTaberna="18",
            PorMisiones="8",
            Otros="17",
            MeritosGastados="36",
            TotalMeritos="25",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=3,
            ArteDeGuerra=6,
            LeccionesClase=9
        },
        HabilidadesNOCombatientes={
            Exploracion=3,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=3,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Jasper Skykru",
        ID="@eruthian16",
        DataGeneral={
            Raza="Bosmer",
            Clase="Guardian",
            Nacimiento="2E 562",
            FechaConvercion="2E 582",
            Sire="Fennorian Ravenwatch",
            Armadura="Ligera",
            Rango="Sanguinaris",
            Orden="Sanguinaris",
            Especializacion="Explorador",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=16,
        Magicka=13,
        Ataque="1D20",
        Defensa=13,
        Meritos={
            PorPorCampana="14",
            PorTaberna="5",
            PorMisiones="2",
            Otros="3",
            MeritosGastados="24",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=6,
            LeccionesClase=9
        },
        HabilidadesNOCombatientes={
            Exploracion=3,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=3,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Jevabelle",
        ID="@GummyKitsu",
        DataGeneral={
            Raza="Breton",
            Clase="Arcanista",
            Nacimiento="",
            FechaConvercion="",
            Sire="Alberich Trevelyan ",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="0",
            PorMisiones="0",
            Otros="1",
            MeritosGastados="0",
            TotalMeritos="2",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Joan Blondhood",
        ID="@NeganProfessional",
        DataGeneral={
            Raza="Khajita",
            Clase="Brujo",
            Nacimiento="2E 564",
            FechaConvercion="2E 582",
            Sire="Veldora Valmir",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="k-Amor",
        ID="@djchon",
        DataGeneral={
            Raza="Altmer",
            Clase="Brujo",
            Nacimiento="2E 590",
            FechaConvercion="2E 621",
            Sire="Vighar",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="1",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="1",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Kenaron",
        ID="@Kenaron",
        DataGeneral={
            Raza="Dunmer",
            Clase="Nigromante",
            Nacimiento="2E 212",
            FechaConvercion="2E 582",
            Sire="Harkon",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Khalen Ashkan",
        ID="@Khalen_Ashkan",
        DataGeneral={
            Raza="Dunmer",
            Clase="Nigromante",
            Nacimiento="2E 491",
            FechaConvercion="2E 576",
            Sire="Vittorio Cercone",
            Armadura="Ligera",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=13,
        Ataque="1D20",
        Defensa=13,
        Meritos={
            PorPorCampana="9",
            PorTaberna="4",
            PorMisiones="2",
            Otros="2",
            MeritosGastados="4",
            TotalMeritos="13",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=2
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="King Krasnyy Drakon",
        ID="@LordKing21",
        DataGeneral={
            Raza="Nordico",
            Clase="Caballero Dragón",
            Nacimiento="1E 800",
            FechaConvercion="1E 840",
            Sire="Desconocido",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="2",
            PorMisiones="0",
            Otros="2",
            MeritosGastados="0",
            TotalMeritos="4",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Leva-Muchas-Anclas",
        ID="@Ilarislasus",
        DataGeneral={
            Raza="Argoniano",
            Clase="Arcanista",
            Nacimiento="",
            FechaConvercion="",
            Sire="",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="1",
            PorMisiones="1",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="2",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Lichit",
        ID="@Berna_Bear",
        DataGeneral={
            Raza="Imperial",
            Clase="Caballero Dragón",
            Nacimiento="2E 591",
            FechaConvercion="2E 616",
            Sire="Veldora Valmir",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Lucien Bloodcrow",
        ID="@Jedi-San",
        DataGeneral={
            Raza="Dunmer",
            Clase="Nigromante",
            Nacimiento="2E 550",
            FechaConvercion="2E 580",
            Sire="Vampiro de Lamae Bal",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="0",
            PorMisiones="0",
            Otros="4",
            MeritosGastados="0",
            TotalMeritos="5",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Mahanarion",
        ID="@Cernunnos050",
        DataGeneral={
            Raza="Altmer",
            Clase="Arcanista",
            Nacimiento="",
            FechaConvercion="",
            Sire="",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="1",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Mepfistófeles",
        ID="@Samyaza01",
        DataGeneral={
            Raza="Altmer",
            Clase="Nigromante",
            Nacimiento="2E 281",
            FechaConvercion="2E 301",
            Sire="Desconocido",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="METALBEER",
        ID="@METALBEER",
        DataGeneral={
            Raza="Dunmer",
            Clase="Nigromante",
            Nacimiento="2E 580",
            FechaConvercion="2E 600",
            Sire="MustPreotecc",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Momon el Negro",
        ID="@clown.28",
        DataGeneral={
            Raza="Nordico",
            Clase="Caballero Dragón",
            Nacimiento="2E 592",
            FechaConvercion="2E 620",
            Sire="Sathas Cercone",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Nahamy Longtail",
        ID="@CC77",
        DataGeneral={
            Raza="Khajita",
            Clase="Hoja de la noche",
            Nacimiento="2E 599",
            FechaConvercion="2E 620",
            Sire="Caster Braveshine",
            Armadura="Ligera",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=13,
        Ataque="1D20",
        Defensa=13,
        Meritos={
            PorPorCampana="1",
            PorTaberna="5",
            PorMisiones="2",
            Otros="5",
            MeritosGastados="10",
            TotalMeritos="3",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=2
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=3,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Nardhil Cercone",
        ID="@Nardhil-CR",
        DataGeneral={
            Raza="Dunmer",
            Clase="Hoja de la noche",
            Nacimiento="2E 601",
            FechaConvercion="2E 616",
            Sire="Desconocido",
            Armadura="Pesada",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=16,
        Meritos={
            PorPorCampana="17",
            PorTaberna="20",
            PorMisiones="7",
            Otros="16",
            MeritosGastados="12",
            TotalMeritos="48",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=6,
            LeccionesClase=2
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Nirelsa Telvanni",
        ID="@Ilarislasus",
        DataGeneral={
            Raza="Dunmer",
            Clase="Nigromante",
            Nacimiento="2E 490",
            FechaConvercion="2E 510",
            Sire="Desconocido",
            Armadura="Pesada",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=16,
        Meritos={
            PorPorCampana="15",
            PorTaberna="12",
            PorMisiones="6",
            Otros="17",
            MeritosGastados="10",
            TotalMeritos="40",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=2
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=3,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Padre Morrison",
        ID="@NightmareXtreme",
        DataGeneral={
            Raza="Imperial",
            Clase="Desconocida",
            Nacimiento="Desconocido",
            FechaConvercion="Desconocido",
            Sire="Nek'Anatari",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Roahrk Vanko",
        ID="@Dodobitus",
        DataGeneral={
            Raza="Imperial",
            Clase="Caballero Dragón",
            Nacimiento="?",
            FechaConvercion="?",
            Sire="Desconocido ",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Roselle",
        ID="@WiscazZz",
        DataGeneral={
            Raza="Breton",
            Clase="Hoja de la noche",
            Nacimiento="2E 603",
            FechaConvercion="2E 620",
            Sire="Vittorio Cercone",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Samael Trevelyan ",
        ID="@eruthian16",
        DataGeneral={
            Raza="Imperial",
            Clase="Arcanista",
            Nacimiento="2E 574",
            FechaConvercion="2E 592 ",
            Sire="Alberich Trevelyan ",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Santiago",
        ID="@LordSantiago20",
        DataGeneral={
            Raza="Nordico",
            Clase="Arcanista",
            Nacimiento="1E 224",
            FechaConvercion="1E 245",
            Sire="Desconocido ",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="4",
            PorMisiones="0",
            Otros="4",
            MeritosGastados="0",
            TotalMeritos="9",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Seint Eilivsen",
        ID="@Seintxx",
        DataGeneral={
            Raza="Nordico",
            Clase="Caballero Dragón",
            Nacimiento="2E 595",
            FechaConvercion="2E 620",
            Sire="Vittorio Cercone",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="1",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="1",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Selene Lavella",
        ID="@eruthian16",
        DataGeneral={
            Raza="Breton",
            Clase="Hoja de la noche",
            Nacimiento="2E 116",
            FechaConvercion="2E 161",
            Sire="Alberich Trevelyan",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Selenya Nyx",
        ID="@Seraphyr",
        DataGeneral={
            Raza="Altmer",
            Clase="Brujo",
            Nacimiento="2E 202",
            FechaConvercion="2E 382",
            Sire="Vittorio Cercone",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Setiar",
        ID="@ALFILER04",
        DataGeneral={
            Raza="Altmer",
            Clase="Brujo",
            Nacimiento="2E 212",
            FechaConvercion="2E 212",
            Sire="Rada al-Saran",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Shameer al-Taneth ",
        ID="@matias_dodo",
        DataGeneral={
            Raza="Guardia Rojo",
            Clase="Caballero Dragón",
            Nacimiento="2E 590",
            FechaConvercion="2E 618",
            Sire="Shiera",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="1",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="2",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Shiera",
        ID="@Gnosis-Aletheia",
        DataGeneral={
            Raza="Breton",
            Clase="Hoja de la noche",
            Nacimiento="2E 594",
            FechaConvercion="2E 618",
            Sire="Alenwen Melethil",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="1",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="1",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Shinn'Khar",
        ID="@eruthian16",
        DataGeneral={
            Raza="Khajita",
            Clase="Hoja de la noche",
            Nacimiento="2E 313",
            FechaConvercion="2E 335 ",
            Sire="Desconocido ",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="0",
            PorMisiones="1",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="2",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Tsui Li'n",
        ID="@Tsuigest",
        DataGeneral={
            Raza="Dunmer",
            Clase="Hoja de la noche",
            Nacimiento="2E 240",
            FechaConvercion="2E 268",
            Sire="Madre",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="0",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="0",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Vadrik Cercone ",
        ID="@eruthian16",
        DataGeneral={
            Raza="Dunmer",
            Clase="Brujo",
            Nacimiento="1E 2816",
            FechaConvercion="2E 18",
            Sire="Vittorio Cercone",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="0",
            PorTaberna="1",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="1",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Veaumont Rosevelt",
        ID="@Vvallb",
        DataGeneral={
            Raza="Breton",
            Clase="Hoja de la noche",
            Nacimiento="2E 590",
            FechaConvercion="2E 620",
            Sire="Vittorio Cercone",
            Armadura="Ligera",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=13,
        Ataque="1D20",
        Defensa=13,
        Meritos={
            PorPorCampana="2",
            PorTaberna="5",
            PorMisiones="1",
            Otros="1",
            MeritosGastados="4",
            TotalMeritos="5",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=2
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Veldora Valmir",
        ID="@OldTaken",
        DataGeneral={
            Raza="Altmer",
            Clase="Nigromante",
            Nacimiento="2E 502",
            FechaConvercion="2E 522",
            Sire="Dimeric Direnni",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="2",
            PorTaberna="1",
            PorMisiones="0",
            Otros="1",
            MeritosGastados="0",
            TotalMeritos="4",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Viktor Blackthorne",
        ID="@AdrianBlackthorne",
        DataGeneral={
            Raza="Dunmer",
            Clase="Hoja de la noche",
            Nacimiento="2E 483",
            FechaConvercion="2E 508",
            Sire="Adrian Blackthorne",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="2",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="3",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Vittorio Cercone",
        ID="@Josh-CR",
        DataGeneral={
            Raza="Dunmer",
            Clase="Hoja de la noche",
            Nacimiento="1E 2809",
            FechaConvercion="1E 2840",
            Sire="Lamae Bal",
            Armadura="Pesada",
            Rango="Regente",
            Orden="Sanguinaris",
            Especializacion="Soldado",
            Profesion="Herrería"
        },
        ProfLevel=1,
        HP=20,
        Magicka=10,
        Ataque="1D20",
        Defensa=17,
        Meritos={
            PorPorCampana="18",
            PorTaberna="22",
            PorMisiones="8",
            Otros="18",
            MeritosGastados="40",
            TotalMeritos="26",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=3,
            ArteDeGuerra=6,
            LeccionesClase=9
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=3,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=3,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="XTROFIEL",
        ID="@XTROFIEL2",
        DataGeneral={
            Raza="Nordico",
            Clase="Hoja de la noche",
            Nacimiento="2E 570",
            FechaConvercion="2E 620",
            Sire="Veloth Cercone",
            Armadura="Ninguna",
            Rango="Vástago",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=12,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="1",
            PorMisiones="1",
            Otros="1",
            MeritosGastados="0",
            TotalMeritos="4",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
    {
        Personaje="Zahir Bloodtide",
        ID="@Jedi-San",
        DataGeneral={
            Raza="Guardia Rojo",
            Clase="Hoja de la noche",
            Nacimiento="",
            FechaConvercion="",
            Sire="",
            Armadura="Ninguna",
            Rango="Iniciado",
            Orden="Ninguna",
            Especializacion="Ninguno",
            Profesion="Profesión"
        },
        ProfLevel=0,
        HP=10,
        Magicka=10,
        Ataque="1D20",
        Defensa=10,
        Meritos={
            PorPorCampana="1",
            PorTaberna="1",
            PorMisiones="0",
            Otros="0",
            MeritosGastados="0",
            TotalMeritos="2",
            Misiones="0"
        },
        HabilidadesCombatientes={
            LinajeCercone=0,
            ArteDeGuerra=0,
            LeccionesClase=0
        },
        HabilidadesNOCombatientes={
            Exploracion=0,
            Investigacion=0,
            InutilizarM=0,
            Sigilo=0,
            Persuacion=0,
            Intimidacion=0,
            Engano=0,
            Voluntad=0,
            Percepcion=0,
            Fuerza=0
        }
    },
}
