CerconeGrimoireData = {
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Asesinato",
        Orden="1",
        Descripcion="Empalamiento:",
        Valores="Acción, Ataque 1d6+2, 3mag y causa sangrado por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Asesinato",
        Orden="2",
        Descripcion="Ataque sorpresa:",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Asesinato",
        Orden="3",
        Descripcion="Abanico de loto:",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sombra",
        Orden="1",
        Descripcion="Capa oscura:",
        Valores="Reacción, +2 Def por 1 turno, 2 mag",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sombra",
        Orden="2",
        Descripcion="Oscuridad devoradora:",
        Valores="Acción adicional, -4 de daño hasta que se consuma, 3mag",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sombra",
        Orden="3",
        Descripcion="Invocar sombra: Invoca una sombra de si mismo que comparte el HP y la Def del NB y obliga al enemigo a atacarla",
        Valores="Acción, Taunt por 1 turno, máximo 3 enemigos, 2 mag, requiere superar tirada de Voluntad",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sifón",
        Orden="1",
        Descripcion="Ofrenda de vida:",
        Valores="Acción, Sanación 1 objetivo 1d4+2, 3 mag, -1HP",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sifón",
        Orden="2",
        Descripcion="Canalización de salud:",
        Valores="Acción, Sanación 4 objetivos 1d3+1, 6 mag, -1HP",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sifón",
        Orden="3",
        Descripcion="Golpes drenadores:",
        Valores="Acción Adicional, +2 HP en el siguiente ataque exitoso que realice el objetivo, 2 mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Señor sepulcral",
        Orden="1",
        Descripcion="Arquero reanimado:",
        Valores="Acción, Ataque 1d6+2, 3mag y causa envenenamiento por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Señor sepulcral",
        Orden="2",
        Descripcion="Mago reanimado:",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Señor sepulcral",
        Orden="3",
        Descripcion="Explosión Pestífera:",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Tirano de los huesos",
        Orden="1",
        Descripcion="Tótem hueso:",
        Valores="Acción adicional, Un uso al dia, 0 Mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Tirano de los huesos",
        Orden="2",
        Descripcion="Armadura de huesos:",
        Valores="Reacción, +2 Def, 2 Mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Tirano de los huesos",
        Orden="3",
        Descripcion="Agarre Sepulcral:",
        Valores="Acción -2 Def, Cost 3Mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Muerte encarnada",
        Orden="1",
        Descripcion="Sanación de carne:",
        Valores="Acción, Sanación 1d4+2 HP, Coste 3Mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Muerte encarnada",
        Orden="2",
        Descripcion="Vida entre la Muerte:",
        Valores="Acción, Sanación 1d3+1 HP a 4 Objetivos, 6 Mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Muerte encarnada",
        Orden="3",
        Descripcion="Resurrección:",
        Valores="Acción, Habilidad en combate, 2 Mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Emisario del Tomo",
        Orden="1",
        Descripcion="Impacto Abisal:",
        Valores="Acción, Ataque 1d6+2, 3mag y causa sangrado por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Emisario del Tomo",
        Orden="2",
        Descripcion="Forjador del Destino:",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Emisario del Tomo",
        Orden="3",
        Descripcion="Ojo Impasible:",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Soldado de Apocrypha",
        Orden="1",
        Descripcion="Defensa Runica:",
        Valores="Reacción, +2 Def por 1 turno, 2 mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Soldado de Apocrypha",
        Orden="2",
        Descripcion="Convulcion Runica:",
        Valores="Acción, Taunt a 3 enemigos por 1 turno, 3mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Soldado de Apocrypha",
        Orden="3",
        Descripcion="Armadura tejida por el destino:",
        Valores="Reacción, 3 defensa a si mismo, 3mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Formas rúnicas curativas",
        Orden="1",
        Descripcion="Curacion Runica:",
        Valores="Sanación 1 objetivo 1d4+2, 3 mag, -1HP",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Formas rúnicas curativas",
        Orden="2",
        Descripcion="Dominio del Arcanista:",
        Valores="Sanación 4 objetivos 1d3+1, 6 mag, -1HP",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Formas rúnicas curativas",
        Orden="3",
        Descripcion="Escudos de Chakram:",
        Valores="Accion, +1 Daño a 1d3 de aliados, 2mag",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Fuego ardiente",
        Orden="1",
        Descripcion="Latigazo fulminante:",
        Valores="Acción, Ataque 1d6+2, 3mag y causa quemadura por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Fuego ardiente",
        Orden="2",
        Descripcion="Aliento abrasador:",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Fuego ardiente",
        Orden="3",
        Descripcion="Infierno:",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Poder draconiano",
        Orden="1",
        Descripcion="Escamas protectoras:",
        Valores="Reacción, +2 Defensa, coste 2 Magicka",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Poder draconiano",
        Orden="2",
        Descripcion="Aliento profundo:",
        Valores="Acción, Taunt a 3 enemigos por 1 turno, coste 2 Magicka",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Poder draconiano",
        Orden="3",
        Descripcion="Gran salto de dragón:",
        Valores="Acción, Stunt por un turno, coste 3 Magicka",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Corazón de tierra",
        Orden="1",
        Descripcion="Nube de cenizas:",
        Valores="Acción, +5 HP a un aliado, coste 3 magicka",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Corazón de tierra",
        Orden="2",
        Descripcion="Fragmento de obsidiana:",
        Valores="Acción, Sanación 4 objetivos +3HP, coste 6 Magicka",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Corazón de tierra",
        Orden="3",
        Descripcion="Armamento Fundido:",
        Valores="Acción adicional, por un turno, este efecto quita 2 pts de daño adicional por los siguientes dos turnos, coste 2 Magicka",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Llamada de la tormenta",
        Orden="1",
        Descripcion="Espinas Demoledoras:",
        Valores="Acción, Ataque 1d6+2, 3mag y causa quemadura por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Llamada de la tormenta",
        Orden="2",
        Descripcion="Escape Relampago:",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Llamada de la tormenta",
        Orden="3",
        Descripcion="Tormenta de Relampagos:",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Magia Oscura",
        Orden="1",
        Descripcion="Tratado Oscuro:",
        Valores="Reacción, +2def un turno, 2mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Magia Oscura",
        Orden="2",
        Descripcion="Prision Runica:",
        Valores="Acción, Taunt a 3 enemigos por 1 turno, 3mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Magia Oscura",
        Orden="3",
        Descripcion="Negacion Magica:",
        Valores="Acción, -1 armadura 1d3 enemigos 1d3 turnos, 5mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Invocacion Daedrica",
        Orden="1",
        Descripcion="Invocar Crepusculo aliado:",
        Valores="Acción, Sanación 1 objetivo 1d4+2, 3 mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Invocacion Daedrica",
        Orden="2",
        Descripcion="Custodia Conjurada:",
        Valores="Acción, Sanación 4 objetivos 1d3+1, 6 mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Invocacion Daedrica",
        Orden="3",
        Descripcion="Armadura Vinculada:",
        Valores="Acción, +1 defensa a 1d3 aliados, 2mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Acompañantes animales",
        Orden="1",
        Descripcion="Netch azul:",
        Valores="Acción adicional para Convocar por primera vez y Acción para el Ataque 1d6+2, 3mag y causa envenenamiento por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Acompañantes animales",
        Orden="2",
        Descripcion="Asolador cortante:",
        Valores="Acción adicional para Convocar por primera vez y Acción para el Ataque 1d8+4, 3mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Acompañantes animales",
        Orden="3",
        Descripcion="Guardián feroz:",
        Valores="Acción adicional para Convocar por primera vez y Acción para el Ataque en área 1d4+1, 4mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Equilibrio verde",
        Orden="1",
        Descripcion="Semilla sanadora:",
        Valores="Sanación 1 objetivo 1d4+2, 3 mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Equilibrio verde",
        Orden="2",
        Descripcion="Proliferación fúngica:",
        Valores="Sanación 4 objetivos 1d3+1, 6 mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Equilibrio verde",
        Orden="3",
        Descripcion="Bendición de loto:",
        Valores="Acción, 1d3+1 Magicka a 1 objetivo, 2 mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Abrazo invernal",
        Orden="1",
        Descripcion="Escudo cristalizado:",
        Valores="Reacción, +2 Def por 1 turno, 2mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Abrazo invernal",
        Orden="2",
        Descripcion="Portal congelado:",
        Valores="Acción, Taunt por 1 turno, máximo 3 enemigos, 2 mag, requiere superar tirada de Voluntad",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Abrazo invernal",
        Orden="3",
        Descripcion="Venganza invernal:",
        Valores="Acción, Stun por 1 turno, 1 objetivo, 3mag",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Lanza Daédrica",
        Orden="1",
        Descripcion="Carga Concentrada:",
        Valores="Acción, Ataque 1d6+2, 3mag y causa quemadura por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Lanza Daédrica",
        Orden="2",
        Descripcion="Golpes Perforantes:",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Lanza Daédrica",
        Orden="3",
        Descripcion="Jabalina Perforadora:",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Ira del ocaso",
        Orden="1",
        Descripcion="Eclipse:",
        Valores="Reacción. +2 Defensa, coste 2 Magicka",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Ira del ocaso",
        Orden="2",
        Descripcion="Opresión radiante:",
        Valores="Acción. Taunt a 3 enemigos por 1 turno, coste 2 Magicka",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Ira del ocaso",
        Orden="3",
        Descripcion="Contragolpe:",
        Valores="Acción. 1+ a todos los dados de aquellos que han recibido daño en el turno anterior, coste 3 Magicka",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Oscuridad restauradora",
        Orden="1",
        Descripcion="Ritual Curativo:",
        Valores="Acción, Sanación 1 objetivo +5HP, coste 3 Magicka",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Oscuridad restauradora",
        Orden="2",
        Descripcion="Rito de paso:",
        Valores="Acción, Sanación 4 objetivos +3HP, coste 6 Magicka",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Oscuridad restauradora",
        Orden="3",
        Descripcion="Honor del Caído:",
        Valores="Acción, Restaura +1 HP a 3 aliados que hayan recibido daño en el turno anterior, coste -2 Magicka",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de una mano",
        Orden="1",
        Descripcion="Doble Arma: Entrenamiento en el combate utilizando dos armas de una mano.",
        Valores="Acción, Ataque 2d3+1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de una mano",
        Orden="2",
        Descripcion="Arma y escudo: Entrenamiento en el combate con un arma de una mano y escudo.",
        Valores="Def +1, Acción, Ataque 1d3+1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de dos manos",
        Orden="1",
        Descripcion="Manodoble: Entrenamiento en el combate con un arma de dos manos.",
        Valores="Acción, Ataque 1d8+1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de dos manos",
        Orden="2",
        Descripcion="Arqueria: Entrenamiento en el combate con arcos cortos y arcos largos.",
        Valores="Acción, Ataque 1d6+1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Bastones",
        Orden="1",
        Descripcion="Bastones de destrucción: Capacidad de lanzar ataques de fuego, hielo y electricidad.",
        Valores="Acción, Ataque 1d6+1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Bastones",
        Orden="2",
        Descripcion="Bastones de restauración: Capacidad de sanar y lanzar ataques de energía.",
        Valores="Acción, Ataque 1d3, Coste 0 Mag. / Acción, Sanación 1d3 HP a 2 aliados, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Técnicas adicionales",
        Orden="1",
        Descripcion="Armas de Asedio: Capacitación para operar las siguientes armas de asedio contra estructuras:",
        Valores="Balistas Acción, Ataque 1d12+3, Ventaja contra armas de asedio, Desventaja contra oponentes en movimiento Coste 0 Mag,\nCatapultas Acción, Ataque 1d12+6, 1 turno de recarga. (0 turno de recarga si hay 1 persona asistiendo),\nTrabuquetes Acción, Ataque 1d12+12, 1 turno de recarga, requiere 2 personas,\nArietes Acción, Ataque 1d12+9 y +3 adicional por cada persona asistiendo (max +18), requiere 3-6 personas.",
    },
    {
        Z="9",
        Nombre="Linaje Cercone",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Seducción Vampírica: Seduce a tu objetivo dándote ventaja en la tirada de persuadir.",
        Valores="Tirada de ventaja a Persuadir, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="9",
        Nombre="Linaje Cercone",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Absorción Vampírica: Atacas a tu oponente con sed de sangre, mientras te curas.",
        Valores="Acción, Ataque +2, + 1d3 HP, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="9",
        Nombre="Linaje Cercone",
        NombreRama="Bloque 3",
        Orden="3",
        Descripcion="Vástago de Sangre: Te transformas en Vástago de Sangre alterando tu forma drásticamente, sanándote y mejorando por un turno tu fuerza de ataque y tu defensa. Si usas esta habilidad en exteriores durante el día recibes 2 pt de daño.",
        Valores="Acción Élite, Ataque +5, Defensa +5, +5 HP, 1 turno, 1 uso al día, (-2 HP, si se usa en exteriores durante el día).",
    },
    {
        Z="10",
        Nombre="Linaje Indómito",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Presencia Indómita: Según la marca obtenida en tu ritual, dicha luna te otorgara un bonificación.\nMasser: Tirada de ventaja en Persuadir\nSecunda: Tirada de ventaja en Intimidar\nLuna Obscura: Tirada de ventaja en Intimidar y Persuadir",
        Valores="Acción, Habilidad fuera de combate, 1 uso al día, Coste 0 Mag.",
    },
    {
        Z="10",
        Nombre="Linaje Indómito",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Devorar: Atacas a tu oponente con furia feral, mientras te curas.",
        Valores="Acción, Ataque +2, + 1d3 HP, 1 uso al día, Coste 0 Mag.",
    },
    {
        Z="10",
        Nombre="Linaje Indómito",
        NombreRama="Bloque 3",
        Orden="3",
        Descripcion="Llamado de la Manada: Invocas 2 lobos para causar un ataque o entras en Berserker potenciando tu forma drásticamente, sanándote y mejorando por un turno tu fuerza de ataque y tu defensa. Por cada Lycan Indómito tu ataque se ve potenciado.",
        Valores="Acción Élite, Ataque +3 (y +1 adicional por cada Lyacn Indómito presente), Defensa +5, +5 HP, 1 turno, 1 uso al día.",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Custodes",
        Orden="1",
        Descripcion="Restablecimiento Arcano: El custode genera un pozo de magicka pura, restaurando 1d3 de magicka a todos los aliados.",
        Valores="Acción adicional Élite, 1d3 magicka a todos los aliados, 1 uso al día.",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Sanguinaris",
        Orden="2",
        Descripcion="Cuerno de Guerra: Soplas un cuerno que eleva la moral de tus aliados, potenciando sus ataques un 1d3 durante 1 turno.",
        Valores="Acción adicional Élite, Bonificación de 1d3 al ataque de aliados cercanos por 1 turno, 1 uso al día.",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Frumentarii",
        Orden="3",
        Descripcion="Subterfugio: El Frumentarii se acerca al enemigo, distrayéndolo, mientras genera un aura de sombras ocultando a 1d3 aliados.",
        Valores="Acción adicional Élite, oculta 1d3 de aliados, 1 uso al día.",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Inquisidores",
        Orden="4",
        Descripcion="Devoción Profana: Realizas un rezo a la Dama de los Lamentos suplicando su ayuda, reviviendo 1d6 de aliados en caso de utilizarse como acción. O reviviéndote a ti mismo, en caso de utilizarse como reacción.",
        Valores="Acción Élite o Acción adicional Élite, Resurrección en masa de 1d6 de aliados, o a si mismo, 1 uso al día.",
    },
    {
        Z="12",
        Nombre="Herrería",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Refuerzos de armadura: Unos refuerzos de armadura que mejoran tu capacidad de resistir golpes fisicos y de hechizos.",
        Valores="Bonificador de Defensa +1 permanente.",
    },
    {
        Z="12",
        Nombre="Herrería",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Herrero del Clan: Técnicas avanzadas que requieren de una mayor aptitud física para la fabricación de armas y armaduras.",
        Valores="Bonificador de Fuerza +1 permanente.",
    },
    {
        Z="12",
        Nombre="Herrería",
        NombreRama="Bloque 3",
        Orden="3",
        Descripcion="Piedras de afilar y contrapeso: Incorporación del uso de las piedras de afilar para hacer mas daños con las armas punzo-cortantes y contrapesos para hacer mas daño con armas contundentes.",
        Valores="Bonificador de +1 a los ataques con Arco, Dagas, Espadas, Hachas y Mazas.",
    },
    {
        Z="13",
        Nombre="Ingeniería de Clockwork",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Ganzúas mejoradas:",
        Valores="Bonificador de Inutilizar Mecanismo +1 permanente",
    },
    {
        Z="13",
        Nombre="Ingeniería de Clockwork",
        NombreRama="Bloque 2",
        Orden="1",
        Descripcion="Fabricante de Clockwork City:",
        Valores="Acción, Ataque +4, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="13",
        Nombre="Ingeniería de Clockwork",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Aturdimiento tonal:",
        Valores="Acción, Stun por 1 turno a un enemigo, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="13",
        Nombre="Ingeniería de Clockwork",
        NombreRama="Bloque 3",
        Orden="1",
        Descripcion="Explosivo:",
        Valores="Acción, Ataque en área +1, 1 uso al día, Coste 0 Mag.",
    },
    {
        Z="14",
        Nombre="Sastrería",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Refuerzos de armadura: Unos refuerzos de armadura que mejoran tu capacidad de resistir golpes fisicos y de hechizos.",
        Valores="Bonificador de Defensa +1 permanente",
    },
    {
        Z="14",
        Nombre="Sastrería",
        NombreRama="Bloque 2",
        Orden="1",
        Descripcion="Armadura Ornamentada: Utiliza tu habilidades de sastre para darte una apariencia mas Noble, y así persuadir mas fácilmente.",
        Valores="Bonificador de persuasión +1 permanente",
    },
    {
        Z="14",
        Nombre="Sastrería",
        NombreRama="Bloque 3",
        Orden="1",
        Descripcion="Empuñadura potenciada: Aprende a fabricar una empuñadura con hilos mágicos que permiten una mejor conducción del ataque mágico.",
        Valores="Bonificador de +1 a los ataques con bastón.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Poción de Regeneración: Bebes una poción previamente creada que cura tus heridas.",
        Valores="Acción adicional, Sanación +3 HP, Coste 0.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 1",
        Orden="2",
        Descripcion="Poción de Magicka: Bebes una poción previamente creada que recupera tu Magicka.",
        Valores="Acción adicional, Recupera +3 Mag, Coste 0.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 2",
        Orden="1",
        Descripcion="Toxicología I Venenos: Lanzas un vial de veneno a tu enemigo causando 2pts de daño cada turno, durante 3 turnos",
        Valores="Acción, Ataque 2pts daño por turno, Duración: 3 turnos, Coste 0 Mag",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Toxicología II Antídotos: Bebes un antídoto previamente preparado que elimina los efectos de envenenamientos.",
        Valores="Acción Adicional, Elimina 2 efectos dañinos en ti, Coste 0 Mag.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 3",
        Orden="1",
        Descripcion="Poción de invisibilidad:  Bebes una poción previamente creada que te hace invisible temporalmente",
        Valores="6 min/2 turnos, Coste 0 Mag.",
    },
}
